services:
  api:
    container_name: qlgd_backend_api
    build: .
    image: vinhuni_qlgd_api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PROJECT_NAME=HỆ THỐNG QUẢN LÝ GIỜ DẠY

  redis:
    image: redis:alpine
    container_name: qlgd_redis
    ports:
      - "6379:6379"
    volumes:
      - qlgd_cache_volume:/data
    command: redis-server --requirepass ITCdhv@1234 --appendonly yes

volumes:
  qlgd_cache_volume:
