version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PROJECT_NAME=Vinhuni Gateway API
    # depends_on:
    #   - db
  
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: db_name
  #   ports:
  #     - "5432:5432"
