from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, BigInteger, NVARCHAR
from sqlalchemy.orm import relationship
from app.models.base import Base

class CQNhomLopHocPhan(Base):
    __tablename__ = "tbl_CQ_NhomLopHocPhan"

    ID = Column(BigInteger, primary_key=True, autoincrement=True, nullable=False)
    MaNhomLopHP = Column(String(50), nullable=False)
    MaLopHP_CMC = Column(String(50), nullable=True)
    TenNhomLopHP = Column(String(200), nullable=True)
    MaHocPhan = Column(String(50), nullable=True)
    HocKy = Column(String(12), nullable=True)
    MaHocKy = Column(Integer, nullable=True)
    MaHTHoc_CMC = Column(Integer, nullable=True)
    SoSinhVien = Column(Integer, nullable=True)
    SoPhong = Column(Integer, nullable=True)
    KhoaHoc = Column(String(80), nullable=True)
    SoTinChi = Column(Float, nullable=True)
    SoTietLT = Column(Float, nullable=True)
    SoTietBT = Column(Float, nullable=True)
    SotietTH = Column(Float, nullable=True)
    PhanPhoiTiet = Column(String(34), nullable=True)
    MaHTHoc = Column(Integer, nullable=True)
    MaHTDay = Column(Integer, nullable=True)
    LopChuyen = Column(Boolean, nullable=True)
    SoTietLTQD = Column(Float, nullable=True)
    SoTietBTQD = Column(Float, nullable=True)
    SoTietTHQD = Column(Float, nullable=True)
    XacNhan = Column(Boolean, nullable=True)
    KhoaCN = Column(String(100), nullable=True)
    GhiChu = Column(String(100), nullable=True)
    MaNhom = Column(String(80), nullable=True)
    HienThi = Column(Boolean, nullable=True)
    NgayBatDau = Column(String(35), nullable=True)
    NgayKetThuc = Column(String(35), nullable=True)
    Thu = Column(String(10), nullable=True)
    TuTiet = Column(String(10), nullable=True)
    SoTiet = Column(String(10), nullable=True)
    HocKyMonHoc = Column(Integer, nullable=True)
    TimeLine = Column(String, nullable=True)  # nvarchar -1
    Dot = Column(Integer, nullable=True)
    IDGiangVien_CMC = Column(String(32), nullable=True)
    XacNhan_Nguoi = Column(String(50), nullable=True)
    XacNhan_ThoiGian = Column(DateTime, nullable=True)
    HS_ID = Column(BigInteger, nullable=True)
    HinhThucHoc_TriNam = Column(String(50), nullable=True)
    NgayBatDau2 = Column(String(35), nullable=True)
    NgayKetThuc2 = Column(String(35), nullable=True)
    Thu2 = Column(String(10), nullable=True)
    TuTiet2 = Column(String(10), nullable=True)
    SoTiet2 = Column(String(10), nullable=True)
    NgayBatDau3 = Column(String(35), nullable=True)
    NgayKetThuc3 = Column(String(35), nullable=True)
    Thu3 = Column(String(10), nullable=True)
    TuTiet3 = Column(String(10), nullable=True)
    SoTiet3 = Column(String(10), nullable=True)
    ID_LanTongHopFile = Column(Integer, nullable=True)
    SiSoDangKyHienTai = Column(Integer, nullable=True)
    SiSoChuyenDoi = Column(Integer, nullable=True)
    SiSoDKH = Column(Integer, nullable=True)
    SotietDA = Column(Float, nullable=True)
    ThanhToanThinhGiang = Column(Integer, nullable=True)
    ThanhToanThinhGiang_GhiChu = Column(String(200), nullable=True)
    TenNhomLopHP_KhongDau = Column(String(200), nullable=True)
    XuLyKeThieuGio = Column(String(20), nullable=True)
    HeSoHocDi = Column(Float, nullable=True)
    IdHocPhan = Column(BigInteger, nullable=True)
    SotietThucTap = Column(Float, nullable=True)
    SotietDoAnKhoaLuan = Column(Float, nullable=True)
    SoTietTH_Tam = Column(Float, nullable=True)
    SoTiet_QuyDoi = Column(Float, nullable=True)
    SoTiet_ThucTe = Column(Float, nullable=True)
    HeSo_LopDong = Column(Float, nullable=True)
    HeSo_Khac = Column(Float, nullable=True)
    HeSo_HeDaoTao = Column(Float, nullable=True)
    NamTaiChinh = Column(Integer, nullable=True)
    Cong_Thuc = Column(NVARCHAR, nullable=True)

    # Relationships
    DSKeKhai = relationship("CQKeKhai", back_populates="NhomLopHocPhan")
